version: "3"

services:

  geth_l2:
    image: ethereumoptimism/go-ethereum:${GETH_L2_TAG:-latest}
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545
    environment:
      - ETH1_ADDRESS_RESOLVER_ADDRESS=${ETH1_ADDRESS_RESOLVER_ADDRESS}

  l1_chain:
    image: ethereumoptimism/hardhat:${L1_CHAIN_TAG:-latest}
    env_file:
      - docker-compose.env
    ports:
      - 9545:9545

  deployer:
    image: ethereumoptimism/deployer:${DEPLOYER_TAG:-latest}
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
